### ISSUE TITLE
Add ability to get XML attributes from documents

### ISSUE THREAD

**Issue by garethrees** [mysociety/icasework-ruby#12]
There can be more than 1 document attached to a case (see https://github.com/mysociety/icasework-ruby/issues/10). We need to filter by `Name` to find the one prefixed "Response":

- [ ] Check that this is the correct assumption and that there's only one "Response" for a case.

We'll also want to filter by `Type` for text extraction.

**Comment by gbp** [comment]
https://stackoverflow.com/a/29431089

**Comment by gbp** [comment]
I don't see why we need to assume there's only one document with the name "Response" for a case?

**Comment by gbp** [comment]
If we really need to do this then it should exist in https://github.com/mysociety/foi-for-councils
