### ISSUE TITLE
Only fetch self-service documents

### ISSUE THREAD

**Issue by garethrees** [mysociety/icasework-ruby#17]
I think we want to set `self_service: true` by default for `Document.find`:

SelfService | Set "True" to return only documents that have been marked as public, or that have been published to the self service portal.
-- | --

Via https://icasework.atlassian.net/wiki/spaces/UsefulFeedback/pages/74586007/GetCaseDocuments+API

**Comment by gbp** [comment]
Since 28aadfb this is now possible in FOIFC
